services:
  - type: web
    name: laravel-app
    env: docker
    repo: https://github.com/Princeaman007/laravel_roles-permissions
    branch: master
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://laravel-app.onrender.com
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          type: private
          name: laravel-mysql
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: laravel
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: rootpassword
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync

    startCommand: |
      php artisan config:cache &&
      php artisan migrate --force &&
      apache2-foreground

  - type: private
    name: laravel-mysql
    env: docker
    dockerfilePath: ""
    image: mysql:8.0
    plan: free
    envVars:
      - key: MYSQL_DATABASE
        value: laravel
      - key: MYSQL_ROOT_PASSWORD
        value: rootpassword
